config/routes.rb
Rails.application.routes.draw do
  get 'home/home'
  resources :stocks
  root to: "stocks#index"
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :stock

  # def intrinsic(log_id)
  #   @log = Log.find(log_id)

  #   bvci=bv_perc_change(@log.stock.symbol)

  #   parr=(@current_bv)*((1+bvci/100.to_f) ** 10)

  #   r = 2.38/100.to_f

  #   cx=@log.coupon*(1-(1/((1+r) ** 10)))/r+parr/((1+r) ** 10) 
  # end

  protected

  # def bv_perc_change(symbol)
  #   @current_bv=book_value(nil)
  #   old_bv= @log.stock.old_bv
  #   years= @log.stock.bv_years
  #   upper=(1/years.to_f)
  #   base=(@current_bv/old_bv.to_f)
  #   a=base**upper
  #   100*(a-1)
  # end


  def book_value
    return (equity.to_d / shares.to_d).round(2)
  end

  def eps
    return (net_income.to_d / shares.to_d).round(2)
  end

  def pe_ratio
    # for every P/E dollars i spend i should receive 1 dollar a year later
    return (price.to_f / eps ).round(2)      
  end
end

app/models/stock.rb
# somehow allow value to be shown for any specific range of time

class Stock < ActiveRecord::Base
  has_many :logs
  validates_uniqueness_of :symbol
  accepts_nested_attributes_for :logs, reject_if: :all_blank, allow_destroy: true

  def intrinsic
    get_stock

    bvci=bv_perc_change

    parr=(@current_bv)*((1+bvci/100.to_f) ** 10)

    r = 2.38/100.to_f

    # last or first coupon by database entry?
    cx=@stock&.logs.present? ? (@stock&.logs&.last&.coupon).to_d*(1-(1/((1+r) ** 10)))/r+parr/((1+r) ** 10) : :needMoreData
  end

  protected

  def bv_perc_change
    @current_bv=book_value
    old_bv= @stock.old_bv
    years= @stock.bv_years
    upper=(1/years.to_f)
    base=(@current_bv/old_bv.to_f)
    a=base**upper
    100*(a-1)
  end


  def book_value
    get_stock  
    return (@stock.logs.map(&:equity).sum.to_d / @stock.logs.map(&:shares).sum.to_d).round(2)
  end

  def eps
    get_stock  
    return (@stock.logs.map(&:net_income).sum.to_d / @stock.logs.map(&:shares).sum.to_d).round(2)
  end

  def pe_ratio
    get_stock  
    # for every P/E dollars i spend i should receive 1 dollar a year later
    return (@stock.logs.map(&:price).sum.to_f / eps ).round(2)      
  end

  def safety(ask)
    get_stock  
    return (ask.to_d / eps ).round(2)
  end

  def get_stock
    @stock = Stock.find_by(symbol: symbol)
  end

end



=begin

debt to equity < .50 (all debt compared to equity)
current assets / current liabilities > 1.50 (debt in the next 12 months)
  

use projected earnings and eps (gem) for prediction of next set of individual/corporate data
Future projections should be visible but inactive - greyed out with the ability to only view. limited clicking and interaction for more detail)


countdown to the next snapshot to gamify account balances

=end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  def index
    @stocks = Stock.all
    debugger
  end

  # GET /admin_actions/1
  # GET /admin_actions/1.json
  def show
  end

  # GET /admin_actions/new
  def new
    @admin_action = Stock.new
  end

  # GET /admin_actions/1/edit
  def edit
  end

  # POST /admin_actions
  # POST /admin_actions.json
  def create
    @admin_action = Stock.new(stock_params)
    
    
    respond_to do |format|
      if @admin_action.save
        
        format.html { redirect_to root_path, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @admin_action }
      else
        format.html { redirect_to new_stock_path }
        format.json { render json: @admin_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_actions/1
  # PATCH/PUT /admin_actions/1.json
  def update
    
    respond_to do |format|
      if @admin_action.update(stock_params)
        format.html { redirect_to root_path, notice: 'Admin action was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_action }
      else
        format.html { render :edit }
        format.json { render json: @admin_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_actions/1
  # DELETE /admin_actions/1.json
  def destroy
    @admin_action.destroy
    respond_to do |format|
      format.html { redirect_to admin_actions_url, notice: 'Admin action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
    
      @admin_action = Stock.find_by(symbol: params[:id])

      if !@admin_action.present?
        redirect_to root_path
        flash[:error] = "That's not in the system"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:symbol, :old_bv, :bv_years, :admin_only, :admin_fav, logs_attributes: [:id, :price, :equity, :shares,:net_income, :bv, :year, :quarter, :coupon, :_destroy])
    end
end

app/helpers/admin_actions_helper.rb
module AdminActionsHelper
end

app/helpers/admin_onlies_helper.rb
module AdminOnliesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<h1>Home#home</h1>
<p>Find me in app/views/home/home.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntrinsicV</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="/assets/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
  <link href="/assets/theme.css" rel="stylesheet" type="text/css" media="all" />
  <link href="/assets/custom.css" rel="stylesheet" type="text/css" media="all" />
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="nav-container">
      <% if flash[:notice] %>
        <div class="text-center alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h3 class="tex-center"><%= flash[:notice] %></h3>
        </div>
      <% elsif flash[:error] %>
        <div class="text-center alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h3 class="tex-center"><%= flash[:error] %></h3>
        </div>
      <% elsif flash[:alert] %>
        <div class="text-center alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h3 class="tex-center"><%= flash[:alert] %></h3>
        </div>
      <% end %>
    </div>
      
    <div class="main-container">
      <%= yield %>
    </div>
    <script src="/assets/jquery.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/parallax.js"></script>
    <script src="/assets/scripts.js"></script>
  </body>
</html>

app/views/stocks/_form.html.erb
<h3>Quarters</h3>
<ul>
  <li>January-March (Q1)</li>
  <li>April-June (Q2)</li>
  <li>July-September (Q3)</li>
  <li>October-December (Q4).</li>
</ul>
<% if @admin_action.errors.any? %>
  <div id="error">
    <h2><%= pluralize(@admin_action.errors.count, "error") %> prohibited this admin_action from being saved:</h2>

    <ul>
    <% @admin_action.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.text_field :symbol, placeholder: "Enter Symbol", required: true %>
<%= f.number_field :old_bv, placeholder: "Oldest BV to date", required: true %>
<%= f.number_field :bv_years, placeholder: "Years between BV", required: true %>
<div id="logs">
  <%= f.fields_for :logs do |log| %>
    <%= render 'log_fields', f: log %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'add log', f, :logs %>
  </div>
</div>



<div class="actions">
  <%= f.submit %>
</div>

app/views/stocks/_log_fields.html.erb
<div class="nested-fields">
    <%= f.number_field :equity, placeholder: "Equity", required: true %>
    <%= f.number_field :shares, placeholder: "Shares", required: true %>
    <%= f.number_field :net_income, placeholder: "Net Income", required: true %>
    <%= f.number_field :coupon, placeholder: "Coupon", step: "any", required: true %>
    <%= f.select :quarter, ["Q1", "Q2", "Q3", "Q4"], required: true %>
    <%= f.select :year, [*(DateTime.now.strftime("%Y").to_i - 5)..DateTime.now.strftime("%Y").to_i].reverse, required: true%>
    <%= link_to_remove_association "remove log", f %>
</div>

app/views/stocks/edit.html.erb
<h1>Editing Admin Action</h1>
<%= form_for(@admin_action, :url => {:action => "update", :id => @admin_action.symbol, :controller => "stocks"}) do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Show', @admin_action %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-hover">
  <tr>
    <th class="text-center">Symbol</th>
    <th class="text-center">Action</th>
    <th class="text-center">Price</th>
    <th class="text-center">Value</th>
  </tr>
  <% @stocks.each do |s| %>
    <tr>
      <td class='text-center'><%= link_to s.symbol.upcase, stock_path(s.symbol) %></td>
      <td class='text-center'>Buy/sell</td>
      <td class='text-center' id='live_price'>$90.34</td>
      <td class='text-center'>$800.32</td>
    </tr>
  <% end %>
</table>

app/views/stocks/new.html.erb
<h1>New Stock</h1>
<%= form_for(@admin_action) do |f| %>
  <%= render 'form', f: f %>
<% end %>
<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<%= link_to 'Edit', edit_stock_path(@admin_action.symbol) %> |
<%= link_to 'Back', stocks_path %>


<section>
  <div class="container">
      <div class="row">
          <div class="col-sm-12">
              <h4 class="uppercase mb80">Historical</h4>
              <div class="tabbed-content button-tabs vertical">
                  <ul class="tabs">
                    <% @admin_action.logs.map(&:year).uniq.each do |year| %>
                      <li>
                          <div class="tab-title">
                              <span><%= year %></span>
                          </div>
                          <div class="tab-content">
                            <table class="table table-hover">
                              <tr>

                                <th class='col-md-1'></th>
                                <th class='col-md-1'>Price</th>
                                <th class='col-md-1'>Equity</th>
                                <th class='col-md-1'>Shares</th> 
                                <th class='col-md-1'>Income</th>
                                <th class='col-md-1'>Dividend</th>
                                <th class='col-md-1'>BV</th>
                                <th class='col-md-1'>EPS</th>
                                <th class='col-md-1'>PE Ratio</th>
                                <th class='col-md-1'>Safety</th>
                              </tr>
                              <% @admin_action.logs.where(year: year).each do |log| %>  
                                <tr>
                                  <td><%= log.quarter %></td>
                                  <td><%= log.price %></td>
                                  <td><%= log.equity %></td>
                                  <td><%= log.shares %></td>
                                  <td><%= log.net_income %></td>
                                  <td><%= log.coupon %></td>
                                  <td><%= Stock.book_value(log.id, nil) %></td>
                                  <td><%= Stock.eps(log.id, nil) %></td>
                                  <td><%= Stock.pe_ratio(log.id, nil) %></td>
                                  <td><%= Stock.safety(log.id, nil) %></td>
                                </tr>
                              <% end %>
                            </table>
                          </div>
                      </li>
                    <% end %>
                  </ul>
              </div>
              
          </div>
      </div>
      
  </div>
</section>